# Generated by Django 3.1 on 2020-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('EmployeeNota', models.CharField(max_length=200)),
                ('DateOfJoining', models.DateField()),
  
            ],
        ),
    ]
